import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
	{ path: '', renderMode: RenderMode.Client },
	{ path: 'login', renderMode: RenderMode.Prerender },
	{ path: 'home', renderMode: RenderMode.Client },
	{ path: 'servicos', renderMode: RenderMode.Client },
	{ path: 'tabela-de-servicos', renderMode: RenderMode.Client },
	{ path: 'clientes', renderMode: RenderMode.Client },
	{ path: 'fornecedores', renderMode: RenderMode.Client },
	{ path: 'ordens-de-servico', renderMode: RenderMode.Client },
	{ path: 'os/scan', renderMode: RenderMode.Client },
	{ path: 'impressao-os', renderMode: RenderMode.Client },
	{ path: 'faturamento', renderMode: RenderMode.Client },
	{ path: 'playground', renderMode: RenderMode.Prerender },
	{ path: 'playground/foundations/colors', renderMode: RenderMode.Prerender },
	{ path: 'playground/foundations/typography', renderMode: RenderMode.Prerender },
	{ path: 'playground/foundations/spacing', renderMode: RenderMode.Prerender },
	{ path: 'playground/foundations/borders', renderMode: RenderMode.Prerender },
	{ path: 'playground/foundations/shadows', renderMode: RenderMode.Prerender },
	{ path: 'playground/components/buttons', renderMode: RenderMode.Prerender },
	{ path: 'playground/components/links', renderMode: RenderMode.Prerender },
	{ path: 'playground/components/cards', renderMode: RenderMode.Prerender },
	{ path: 'playground/components/forms', renderMode: RenderMode.Prerender },
	{ path: 'playground/components/dropdowns', renderMode: RenderMode.Prerender },
	{ path: 'playground/components/feedback', renderMode: RenderMode.Prerender },
	{ path: 'playground/components/overlays', renderMode: RenderMode.Prerender },
	{ path: '**', renderMode: RenderMode.Prerender },
];
